# Generated by Django 5.0.7 on 2024-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='comment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
