# Generated by Django 5.0.7 on 2024-07-27 17:36

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=tasks.models.get_current_date),
        ),
    ]
